<h2>Tasks</h2>
<hr>
<div class="">
    <p>Add solution to tasks to the "Solution" tab.</p>
    <p><b>1.</b> Use the function "getTable()" from module\Application\Service\Data.php and render it like the image below shows. The data can be found in module\Application\src\Service\data.json. Note, style is optional.</p>
    <img src="img/preview-table.PNG" alt="" style="max-width:600px">
    <p>You should be able to add any number to columns R1, R2, R3. Updating any of those fields should automatically calculate a value for the columns Average and Sum.</p>
    <p>Average = (R1 + R2 + R3) / 3</p>
    <p>Sum = R1 + R2 + R3</p>
</div>
<hr>
<div class="">
    <p><b>2.</b> Add a button called "Add Row". Clicking this button should append a new row to the table with no data in any of the columns. Each added row should have independent calculations for average and sum.</p>
</div>
<hr>
<div class="">
    <p><b>3.</b> To each added row, add a button to remove the added row.</p>
</div>
<hr>
<div class="">
    <p><b>4.</b> Add a submit button. Clicking this button should get all input data and store it in a new file called "report.json".</p>
</div>
<hr>
<div class="">
    <p><b>5.</b> In the tab "Report", render out the collected data in anyway you feel like.</p>
</div>
<hr>
<div class="">
    When finished with tasks, add the full code base to a new repository on GitHub and send the link for review.
</div>
